### ISSUE TITLE
missing dependency node-hue-api

### ISSUE THREAD

**Issue by aaronpk** [bitfocus/companion-module-phillips-hue#1]
It looks like `package.json` doesn't define the `node-hue-api` dependency so it's not being installed in the Companion build?

**Comment by PhotoJoseph** [comment]
What @aaronpk said… I see these errors when trying to add the **Hue** instance:

04. 15:58:22 module(phillips-hue): Error loading module: Error: Cannot find module 'node-hue-api' Require stack: - /Applications/Companion.app/Contents/Resources/app.asar/lib/module/phillips-hue/lib/getAllGroups.js - /Applications/Companion.app/Contents/Resources/app.asar/lib/module/phillips-hue/index.js - /Applications/Companion.app/Contents/Resources/app.asar/lib/instance.js - /Applications/Companion.app/Contents/Resources/app.asar/app.js - /Applications/Companion.app/Contents/Resources/app.asar/electron.js -

<img width="658" alt="Screen Shot 2021-02-04 at 3 58 26 PM" src="https://user-images.githubusercontent.com/78106443/106970550-f7813380-6701-11eb-8100-4b874af13e0b.png">

**Comment by mattehalen** [comment]
This should be fixed in the latest beta release.

! KNOW BUG
Needs a restart of companion after entering the username and pressing Apply changes.
