### ISSUE TITLE
[Feature] Poll /api/<username>/lights and /groups for allowing feedback on buttons

### ISSUE THREAD

**Issue by Wiethoofd** [bitfocus/companion-module-phillips-hue#10]
Currently it is not possible to add a 'feedback' to a button controlling a light or room, however the npm-hue-api [`lights.getAll()`](https://github.com/peter-murray/node-hue-api/blob/typescript/docs/lights.md#getAll) and [`rooms.getAll()`](https://github.com/peter-murray/node-hue-api/blob/typescript/docs/groups.md#getall) should contain blobs of full states of the lamps and rooms for possibly offering individual feedback options when stored and could potentially polled every x seconds, seeing as the API and Bridge is limited to up to 12 requests per second.

Additionally when triggering an action to change an individual lamp or room it could use the `getLight()` or `getLightAttributesAndState()` (and respective room function equivalents) for updating those potentially polled states, if not request and set it and assume that is the correct state for the feedback you can then have set on a button.

**Comment by MegaAdragon** [comment]
I already have a local version that allows to add feedback for lights or rooms. I have to clean up some stuff first, but I will create a PR so you can try it for yourself.

**Comment by MegaAdragon** [comment]
Resolved by #13

Polling interval can be set in the module configuration:
<img width="146" alt="image" src="https://github.com/user-attachments/assets/2d575d35-2a21-4434-8156-d782ffcaa8b8">
