### ISSUE TITLE
Warning Syncing loop

### ISSUE THREAD

**Issue by jwildeboer** [bitfocus/companion-module-phillips-hue#11]
After upgrading to 3.0.0 on my Mac, the Philips Hue module goes into a loop between OK and "Warning Syncing". The log file says:

system: ** Log cleared **
error: /Applications/Companion.app/Contents/Resources/module-legacy/manifests/companion-module-phillips-hue/index.js:1
(()=>{var __webpack_modules__={29462:(e,t,n)=>{const r=n(73837);var i=n(62325);const s=global.modulePkg;if(!s)throw new Error("Missing module package.json data");function o(e,t,r){var o=this;for(var a in o.system=e,o.id=t,o.config=r,o.package_info=s,o.Image=o.system.Image,o.label=r.label,o.defineConst("debug",n(15158)("instance:"+o.package_info.name+":"+o.id)),o.defineConst("log",(function(e,t){this.system.sendLog(e,t)})),i)o.defineConst(a,i[a]);o.defineConst("REGEX_IP","/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/"),o.defineConst("REGEX_HOSTNAME","/^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9])$/"),o.defineConst("REGEX_BOOLEAN","/^(true|false|0|1)$/i"),o.defineConst("REGEX_PORT","/^([1-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]|[1-8][0-9]{3}|9[0-8][0-9]{2}|99[0-8][0-9]|999[0-9]|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-4])$/"),o.defineConst("REGEX_PERCENT","/^(100|[0-9]|[0-9][0-9])$/"),o.defineConst("REGEX_FLOAT","/^([0-9]*\\.)?[0-9]+$/"),o.defineConst("REGEX_FLOAT_OR_INT","/^([0-9]+)(\\.[0-9]+)?$/"),o.defineConst("REGEX_SIGNED_FLOAT","/^[+-]?([0-9]*\\.)?[0-9]+$/"),o.defineConst("REGEX_NUMBER","/^\\d+$/"),o.defineConst("REGEX_SOMETHING","/^.+$/"),o.defineConst("REGEX_SIGNED_NUMBER","/^[+-]?\\d+$/"),o.defineConst("REGEX_TIMECODE","/^(0*[0-9]|1[0-9]|2[0-4]):(0*[0-9]|[1-5][0-9]|60):(0*[0-9]|[1-5][0-9]|60):(0*[0-9]|[12][0-9]|30)$/"),o.defineConst("CHOICES_YESNO_BOOLEAN",[{id:"true",label:"Yes"},{id:"false",label:"No"}]),o.defineConst("STATE_UNKNOWN",null),o.defineConst("STATE_OK",0),o.defineConst("STATE_WARNING",1),o.defineConst("STATE_ERROR",2),o.defineConst("STATUS_UNKNOWN",null),o.defineConst("STATUS_OK",0),o.defineConst("STATUS_WARNING",1),o.defineConst("STATUS_ERROR",2),o.currentStatus=o.STATUS_UNKNOWN,o.currentStatusMessage="",e.on("instance_actions",(function(e,t){o.setActions(t)})),e.on("variable_parse",(function(e,t){o.system.parseVariables(e,t)})),e.on("osc_send",(function(e,t,n,r){o.oscSend(e,t,n,r)})),e.on("log",(function(e,t,n){o.sendLog(t,n)}))}o.prototype.defineConst=function(e,t){Object.defineProperty(this,e,{value:t,enumerable:!0,writable:!1})},o.prototype.rgb=(e,t,n,r=10)=>(e=parseInt(e,r),t=parseInt(t,r),n=parseInt(n,r),!(isNaN(e)||isNaN(t)||isNaN(n))&&(255&e)<<16|(255&t)<<8|255&n),o.prototype.rgbRev=e=>({r:(16711680&(e=Math.round(e)))>>16,g:(65280&e)>>8,b:255&e}),o.prototype.status=function(e,t){var n=this;n.currentStatus==e&&n.currentStatusMessage==t||(n.currentStatus=e,n.currentStatusMessage=t,n.system.sendStatus(e,t))},o.prototype.saveConfig=function(){this.system.saveConfig(this.config)},o.CreateConvertToBooleanFeedbackUpgradeScript=function(e){return function(t,n,r,i){let s=!1;for(const t of i){let n=e[t.type];if(!0===n&&(n={bg:"bgcolor",bgcolor:"bgcolor",fg:"color",color:"color",png64:"png64",png:"png64"}),n){t.style||(t.style={});for(const[e,r]of Object.entries(n))void 0!==t.options[e]&&(t.style[r]=t.options[e],delete t.options[e],s=!0)}}return s}},o.prototype.addUpgradeScript=function(){throw new Error("addUpgradeScript has been removed and replaced by a new static GetUpgradeScripts flow. Check the wiki for more information")},o.prototype.setActions=function(e){var t=this;t.system.setActions(e,t.action&&t.action.bind(t))},o.prototype.setVariableDefinitions=function(e){this.system.setVariableDefinitions(e)},o.prototype.setVariable=function(e,t){this.system.setVariable(e,t)},o.prototype.setVariables=function(e){"object"==typeof e&&this.system.setVariables(e)},o.prototype.getVariable=function(e,t){this.system.getVariable(e,t)},o.prototype.parseVariables=function(e,t){this.system.parseVariables(e,t)},o.prototype.setFeedbackDefinitions=function(e){var t=this;t.system.setFeedbackDefinitions(e,t.feedback&&t.feedback.bind(t))},o.prototype.setPresetDefinitions=function(e){this.system.setPresetDefinitions(e)},o.prototype.checkFeedbacks=function(...e){return this.system.checkFeedbacks(...e)},o.prototype.checkFeedbacksById=function(...e){return this.system.checkFeedbacksById(...e)},o.prototype.getAllFeedbacks=function(){return this.system.getAllFeedbacks()},o.prototype.subscribeFeedbacks=function(e){return this.system.subscribeFeedbacks(e)},o.prototype.unsubscribeFeedbacks=function(e){return this.system.unsubscribeFeedbacks(e)},o.prototype.getAllActions=function(){return this.system.getAllActions()},o.prototype.subscribeActions=function(e){return this.system.subscribeActions(e)},o.prototype.unsubscribeActions=function(e){return this.system.unsubscribeActions(e)},o.prototype.oscSend=function(e,t,n,r){this.system.oscSend(e,t,n,r)},o.extendedBy=function(e){r.inherits(e,o)},e.exports=o},62325:e=>{e.exports={ICON_POWER_UNKNOWN:"iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6CAYAAAATBx+NAAABJmlDQ1BBZG9iZSBSR0IgKDE5OTgpAAAoz2NgYDJwdHFyZRJgYMjNKykKcndSiIiMUmA/z8DGwMwABonJxQWOAQE+IHZefl4qAwb4do2BEURf1gWZxUAa4EouKCoB0n+A2CgltTiZgYHRAMjOLi8pAIozzgGyRZKywewNIHZRSJAzkH0EyOZLh7CvgNhJEPYTELsI6Akg+wtIfTqYzcQBNgfClgGxS1IrQPYyOOcXVBZlpmeUKBhaWloqOKbkJ6UqBFcWl6TmFit45iXnFxXkFyWWpKYA1ULcBwaCEIWgENMAarTQZKAyAMUDhPU5EBy+jGJnEGIIkFxaVAZlMjIZE+YjzJgjwcDgv5SBgeUPQsykl4FhgQ4DA/9UhJiaIQODgD4Dw745AMDGT/0ZOjZcAAAACXBIWXMAAAsTAAALEwEAmpwYAAAN0GlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAxOC0wNi0wNFQwMDowNzoyNSswMjowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOC0wNi0wNFQxNjo0OToyNyswMjowMCIgeG1wOk1vZGlmeURhdGU9IjIwMTgtMDYtMDRUMTY6NDk6MjcrMDI6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmU0YmQzODYyLWRmOWYtNDQxOC1iNWNmLTE3MTUwNzE0ODg0ZiIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOmYwZmFmYmM0LTc0MmEtMmE0NS1iMjBkLWU4NWQ2NmZhZjEzNyIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOmNlZDYyMWNiLTU3MmItNGMyZS1hYTU4LTUwYTJiN2YwYzNjZCIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9IkFkb2JlIFJHQiAoMTk5OCkiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmNlZDYyMWNiLTU3MmItNGMyZS1hYTU4LTUwYTJiN2YwYzNjZCIgc3RFdnQ6d2hlbj0iMjAxOC0wNi0wNFQwMDowNzoyNSswMjowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo0YmM0OWQzYi05YzRmLTRkNmQtODQyNi0yNzlmYzc3YjI2NWMiIHN0RXZ0OndoZW49IjIwMTgtMDYtMDRUMTY6MTA6MTIrMDI6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAoTWFjaW50b3NoKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6NGJmNDFmYTctZTNmMi00NzdiLWIzMjktMDQ3NzU2NzhjOWMwIiBzdEV2dDp3aGVuPSIyMDE4LTA2LTA0VDE2OjQ5OjI3KzAyOjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgQ0MgKE1hY2ludG9zaCkiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNvbnZlcnRlZCIgc3RFdnQ6cGFyYW1ldGVycz0iZnJvbSBhcHBsaWNhdGlvbi92bmQuYWRvYmUucGhvdG9zaG9wIHRvIGltYWdlL3BuZyIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iZGVyaXZlZCIgc3RFdnQ6cGFyYW1ldGVycz0iY29udmVydGVkIGZyb20gYXBwbGljYXRpb24vdm5kLmFkb2JlLnBob3Rvc2hvcCB0byBpbWFnZS9wbmciLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmU0YmQzODYyLWRmOWYtNDQxOC1iNWNmLTE3MTUwNzE0ODg0ZiIgc3RFdnQ6d2hlbj0iMjAxOC0wNi0wNFQxNjo0OToyNyswMjowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+I
Starting up module class: k
Sentry disabled
Module-host accepted registration
error: /Applications/Companion.app/Contents/Resources/module-legacy/manifests/companion-module-phillips-hue/index.js:1
(()=>{var __webpack_modules__={29462:(e,t,n)=>{const r=n(73837);var i=n(62325);const s=global.modulePkg;if(!s)throw new Error("Missing module package.json data");function o(e,t,r){var o=this;for(var a in o.system=e,o.id=t,o.config=r,o.package_info=s,o.Image=o.system.Image,o.label=r.label,o.defineConst("debug",n(15158)("instance:"+o.package_info.name+":"+o.id)),o.defineConst("log",(function(e,t){this.system.sendLog(e,t)})),i)o.defineConst(a,i[a]);o.defineConst("REGEX_IP","/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/"),o.defineConst("REGEX_HOSTNAME","/^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9])$/"),o.defineConst("REGEX_BOOLEAN","/^(true|false|0|1)$/i"),o.defineConst("REGEX_PORT","/^([1-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]|[1-8][0-9]{3}|9[0-8][0-9]{2}|99[0-8][0-9]|999[0-9]|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-4])$/"),o.defineConst("REGEX_PERCENT","/^(100|[0-9]|[0-9][0-9])$/"),o.defineConst("REGEX_FLOAT","/^([0-9]*\\.)?[0-9]+$/"),o.defineConst("REGEX_FLOAT_OR_INT","/^([0-9]+)(\\.[0-9]+)?$/"),o.defineConst("REGEX_SIGNED_FLOAT","/^[+-]?([0-9]*\\.)?[0-9]+$/"),o.defineConst("REGEX_NUMBER","/^\\d+$/"),o.defineConst("REGEX_SOMETHING","/^.+$/"),o.defineConst("REGEX_SIGNED_NUMBER","/^[+-]?\\d+$/"),o.defineConst("REGEX_TIMECODE","/^(0*[0-9]|1[0-9]|2[0-4]):(0*[0-9]|[1-5][0-9]|60):(0*[0-9]|[1-5][0-9]|60):(0*[0-9]|[12][0-9]|30)$/"),o.defineConst("CHOICES_YESNO_BOOLEAN",[{id:"true",label:"Yes"},{id:"false",label:"No"}]),o.defineConst("STATE_UNKNOWN",null),o.defineConst("STATE_OK",0),o.defineConst("STATE_WARNING",1),o.defineConst("STATE_ERROR",2),o.defineConst("STATUS_UNKNOWN",null),o.defineConst("STATUS_OK",0),o.defineConst("STATUS_WARNING",1),o.defineConst("STATUS_ERROR",2),o.currentStatus=o.STATUS_UNKNOWN,o.currentStatusMessage="",e.on("instance_actions",(function(e,t){o.setActions(t)})),e.on("variable_parse",(function(e,t){o.system.parseVariables(e,t)})),e.on("osc_send",(function(e,t,n,r){o.oscSend(e,t,n,r)})),e.on("log",(function(e,t,n){o.sendLog(t,n)}))}o.prototype.defineConst=function(e,t){Object.defineProperty(this,e,{value:t,enumerable:!0,writable:!1})},o.prototype.rgb=(e,t,n,r=10)=>(e=parseInt(e,r),t=parseInt(t,r),n=parseInt(n,r),!(isNaN(e)||isNaN(t)||isNaN(n))&&(255&e)<<16|(255&t)<<8|255&n),o.prototype.rgbRev=e=>({r:(16711680&(e=Math.round(e)))>>16,g:(65280&e)>>8,b:255&e}),o.prototype.status=function(e,t){var n=this;n.currentStatus==e&&n.currentStatusMessage==t||(n.currentStatus=e,n.currentStatusMessage=t,n.system.sendStatus(e,t))},o.prototype.saveConfig=function(){this.system.saveConfig(this.config)},o.CreateConvertToBooleanFeedbackUpgradeScript=function(e){return function(t,n,r,i){let s=!1;for(const t of i){let n=e[t.type];if(!0===n&&(n={bg:"bgcolor",bgcolor:"bgcolor",fg:"color",color:"color",png64:"png64",png:"png64"}),n){t.style||(t.style={});for(const[e,r]of Object.entries(n))void 0!==t.options[e]&&(t.style[r]=t.options[e],delete t.options[e],s=!0)}}return s}},o.prototype.addUpgradeScript=function(){throw new Error("addUpgradeScript has been removed and replaced by a new static GetUpgradeScripts flow. Check the wiki for more information")},o.prototype.setActions=function(e){var t=this;t.system.setActions(e,t.action&&t.action.bind(t))},o.prototype.setVariableDefinitions=function(e){this.system.setVariableDefinitions(e)},o.prototype.setVariable=function(e,t){this.system.setVariable(e,t)},o.prototype.setVariables=function(e){"object"==typeof e&&this.system.setVariables(e)},o.prototype.getVariable=function(e,t){this.system.getVariable(e,t)},o.prototype.parseVariables=function(e,t){this.system.parseVariables(e,t)},o.prototype.setFeedbackDefinitions=function(e){var t=this;t.system.setFeedbackDefinitions(e,t.feedback&&t.feedback.bind(t))},o.prototype.setPresetDefinitions=function(e){this.system.setPresetDefinitions(e)},o.prototype.checkFeedbacks=function(...e){return this.system.checkFeedbacks(...e)},o.prototype.checkFeedbacksById=function(...e){return this.system.checkFeedbacksById(...e)},o.prototype.getAllFeedbacks=function(){return this.system.getAllFeedbacks()},o.prototype.subscribeFeedbacks=function(e){return this.system.subscribeFeedbacks(e)},o.prototype.unsubscribeFeedbacks=function(e){return this.system.unsubscribeFeedbacks(e)},o.prototype.getAllActions=function(){return this.system.getAllActions()},o.prototype.subscribeActions=function(e){return this.system.subscribeActions(e)},o.prototype.unsubscribeActions=function(e){return this.system.unsubscribeActions(e)},o.prototype.oscSend=function(e,t,n,r){this.system.oscSend(e,t,n,r)},o.extendedBy=function(e){r.inherits(e,o)},e.exports=o},62325:e=>{e.exports={ICON_POWER_UNKNOWN:"iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6CAYAAAATBx+NAAABJmlDQ1

**Comment by jwildeboer** [comment]
I guess it's this: "throw new Error("addUpgradeScript has been removed and replaced by a new static GetUpgradeScripts flow. Check the wiki for more information")" but I am not sure how to proceed in finding out more and possibly help with a fix.

**Comment by ktamas77** [comment]
Same thing keeps happening with me - I think Philips Hue is simply broken with v3.0
