### ISSUE TITLE
Incompatible with Companion 3.0?

### ISSUE THREAD

**Issue by jwildeboer** [bitfocus/companion-module-phillips-hue#12]
Seems this module isn't included in Companion 3.0 as default plug-in and it stopped working with 

`throw new Error("addUpgradeScript has been removed and replaced by a new static GetUpgradeScripts flow. Check the wiki for more information")`

when you try to use it. Any plans to make it work with 3.0 or is this module now unmaintained?

Jan

**Comment by josephdadams** [comment]
Some modules that are "legacy", meaning they have not been upgraded to the 3.0 api simply don't work. I would suggest reaching out to the module author directly.

`"author": "Mathias Halén <matte_halen@hotmail.com>"`

**Comment by mattehalen** [comment]
Hi.

I'm not going to be able to keep this module up to date at the moment. 

Sorry for the inconvenience this may have caused you.

**Comment by MegaAdragon** [comment]
I did the last major changes to the module and I can try to upgrade it to 3.0. 
However, I'm on vacation right now, I will be back in the beginning of September. 

I guess I will have to request ownership of the module first, in order to maintain the repo in the future.

**Comment by josephdadams** [comment]
I can grant you access @MegaAdragon

**Comment by josephdadams** [comment]
done

**Comment by ktamas77** [comment]
same issues/request here, please let me know if there is any updates and/or if there is anything i can help with.

**Comment by MegaAdragon** [comment]
Ok, so I tried a few things, but it looks like rewriting / refactoring the whole module for v3.0 is the easiest way...

I let you know once I finished the PR. For now I still have to find out how the new changes work...

**Comment by ktamas77** [comment]
> I let you know once I finished the PR and you can test it. For now I still have to find out how the new changes work... 

Awesome thank you for working on this!

**Comment by MegaAdragon** [comment]
@ktamas77 
I tested with my setup and everything is running as expected now.
Feel free to try it out! Just clone my branch into the companion-module-dev folder and the hue module should work again.

Only thing that does not work at the moment is the “Save” button. Don’t know why, but you have to disable / enable the module for the changes to applies…

**Comment by ktamas77** [comment]
thats's fantastic! amazing work will test & get back to you shortly. thank you so much!

**Comment by ktamas77** [comment]
tried to test it, but couldn't make it work. did it make it to the official release? if so, i'll try again at the next update.
i appreciate your efforts, thanks again!

**Comment by MegaAdragon** [comment]
> tried to test it, but couldn't make it work. did it make it to the official release? if so, i'll try again at the next update. i appreciate your efforts, thanks again!

Nope, since I haven't merged my changes yet, it is not part of any new release. That's why I wrote:

> Just clone my branch into the companion-module-dev folder and the hue module should work again.

**Comment by HugoR07** [comment]
Hi, 
I need to use companion and the HUE module but im on companion V3. Should i update the module for V3 or do i need to use an older version of companion.

My goal is to use « trigger scene » who’s actually not working because « ??? » in the scene selection on companion.
