### ISSUE TITLE
Error: Problems resolving hue bridges, unable to get local issuer certificate

### ISSUE THREAD

**Issue by odedd** [bitfocus/companion-module-phillips-hue#3]
Hi.
I was using this module for several months to control my hue lights, and this used to work great for several months. Several days ago, without anything I can recall doing, it stopped connecting to the hue bridge. Please notice that my iphone app still manages to connect just fine.

I'm a beginner in the world of node.js (to say the least), but from looking at the logs, I see the following error message:
`Problems resolving hue bridges, unable to get local issuer certificate.`
It seems to come from the node-hue-api side of things.

I'm running macos 11.6.2 (big sur).
I've tried factory resetting my hue bridge but to no avail.

Any idea what might be causing that? Is that something on my system or a widespread issue?

Thank you very much

**Comment by odedd** [comment]
Update: I have also reported an issue over at node-hue-api as I wasn't sure which is the culprit.
Anyway - according to [this](https://github.com/peter-murray/node-hue-api/issues/208#issuecomment-1008116548) reply over there there appears to have been a certificate update on Jan 4th at https://discovery.meethue.com which causes this to happen.

**Comment by mattehalen** [comment]
I'm looking into this problem now and see what I can fix.
I think I need to start over with this plugin to get it to work more as I want.

But in the meantime I think you can use a GENERIC HTTTP Request.
URL: http://192.168.8.184/api/uC9dWT02LoVZ3vneN9qruCk6B3ToU8hNdVcsNLEV/lights/44/state
http://<YOUR HUB IP>/api/<YOUR USERNAME>/lights/44/state


![image](https://user-images.githubusercontent.com/16779335/148764482-1675739f-306a-41a7-9094-f601fc06289a.png)

**Comment by emilevdende** [comment]
I also just ran into this issue. It ran perfectly using the module that @mattehalen built (chapeau!) but a few days ago it stopped. Would love to see this come back to life again.

**Comment by odedd** [comment]
I made a PR over at https://github.com/peter-murray/node-hue-api/pull/209 which fixes it. As soon as they merge it there, it can be incorporated here and the issue will be fixed. I already tested it and it seems to solve the problem.

**Comment by emilevdende** [comment]
great, that would be awesome

**Comment by odedd** [comment]
Well, it seems that just as I was writing the above, [v4.0.11](https://github.com/peter-murray/node-hue-api/commit/730b0cb6265121a0df6ac257cb1a6e474521c2b3) of node-hue-api was released, with the fix in it.

**Comment by mattehalen** [comment]
Just bumped the node-hue-api to use your update and it works over here. Just need admins to implement it in their releases.

**Comment by emilevdende** [comment]
Not sure about the process of admins implementing this in the companion release - how long would that generally take @mattehalen ?

**Comment by emilevdende** [comment]
Or, can I manually update a module inside companion?

**Comment by mattehalen** [comment]
Are you using the main version of Companion or a Beta version?
Main version 
https://bitfocus.io/user/downloads

Beta versions:
https://bitfocus.io/companion/download/builds/
![image](https://user-images.githubusercontent.com/16779335/149142171-18904672-c20f-45cd-9db4-1a5da08f1e31.png)
These version have the update.

Don't know when main version of Companion will update.

**Comment by emilevdende** [comment]
That's great, thanks! I do run the beta version - how would I install the updated package? (running companionPi)
